### ISSUE TITLE
Erro no método getBooleanFromString e blockeByConfig

### ISSUE THREAD

**Issue by pedrominare** [felps18/otxserver#3]
Na pasta mods, na mesma raiz que a pasta data, tenho custom_commands.xml que possui um script de bless. O script faz uso do método getBooleanFromString e não o encontra ao rodar a distro.
Erro na lib data/lib/deletebra_lib.lua no blockeByConfig. (Ocorre na execucao dos arquivos data que vem na propria source).

**Comment by felps18** [comment]
creio que você deve ter retirado do config.lua o
"blockedVps = "google;amazon;amazon.com;oracle;azure;vultr;google.com" "
independente, pode retirar a função toda da deletebra_lib
https://github.com/felps18/otxserver/blob/3b7cb27e9d19c8329f85c48aa3666359b9f7f33c/data/lib/deletebra_lib.lua#L503
retire da sua lib, da linha 503 até 528, assim irá retirar o problema do blockedVps não estar configurado.

Essa função fica pesada pro servidor rodar junto ao server, desnecessário usa-la ou configura-la.

**Comment by pedrominare** [comment]
Então, não havia retirado o blockedVps do config.lua, mas vou excluir o método do deletebra_lib.lua e remover do config. Agora com relação ao método getBooleanFromString, acredito que os mods/ não estão conseguindo fazer uso da função. Sabe me dizer se é necessário importar esse método da lib 011-string.lua para que seja usado nos mods? Se sim, como?
